@startuml
left to right direction

:user: as u

component [Prompt] as prompt

cloud {
    database database as vdb
    component [Retriever] as rag
    rag --> vdb
    vdb --> rag
}

u   --> rag
rag --> prompt


@enduml